version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - zip -r app.zip . -x "*.git*" "*.github*" "*__pycache__*"
artifacts:
  files:
    - app.zip
